### ISSUE TITLE
webpack loaders -loader suffix

### ISSUE THREAD

**Issue by sag1v** [coryhouse/pluralsight-reusable-components-cra#3]
Hi Cory, can't wait to watch this course :)
While browsing around the files i noticed the way you configure the webpack's `loaders`.
As far as i know, in webpack 2 we can't or shouldn't omit the `-loader` suffix anymore  [#444](https://github.com/aspnet/JavaScriptServices/issues/444) and  [Docs](https://webpack.js.org/concepts/loaders/#resolving-loaders). 
So this: 
` loader: 'babel',` 

Should be like this:
` loader: 'babel-loader',`

Though, there is a way to add it in a centralized place via `moduleExtensions`  [Docs](https://webpack.js.org/configuration/resolve/#resolveloader-moduleextensions).
The project is looking great, keep up the good work!

**Comment by coryhouse** [comment]
Thanks for the comment! I'm using the current create-react-app, which doesn't have webpack 2 yet. 

When they'll upgrade, I plan to upgrade the relevant parts of the course.

Thanks!

**Comment by sag1v** [comment]
Silly me!
